local enum = require("../classes/enum")
local any = require("../classes/any")

local a = enum()

assert(a:add_value(any("A")) == 1)
assert(a.A == 1)
assert(a:add_value(any("B"), 5) == 5)
assert(a.B == 5)
assert(a:add_value(any("C"), "c") == 6)
assert(a.C == 6)
assert(a:add_value(any("D"), "d", 10) == 10)
assert(a.D == 10)
assert(a:add_value(any("E"), 10) == 11)
assert(a.E == 11)
assert(a 'add' {"F", "f"} == 12)

assert(a:get_value("A") == 1)
assert(a:get_value("B") == 5)
assert(a:get_value("C") == 6)
assert(a:get_value("D") == 10)
assert(a:get_value("E") == 11)
assert(a:get_value("F") == 12)

assert(a:get_key(1) == "A")
assert(a:get_key(5) == "B")
assert(a:get_key(6) == "C")
assert(a:get_key(10) == "D")
assert(a:get_key(11) == "E")
assert(a:get_key(12) == "F")

assert(a:get_string(a.A) == "")
assert(a:get_string(a.B) == "")
assert(a:get_string(a.C) == "c")
assert(a:get_string(a.D) == "d")
assert(a:get_string(a.E) == "")
assert(a:get_string(a.F) == "f")

print("class 'enum' tests passed")
